### ISSUE TITLE
YOSRequestClient ignores the query string for PUT requests

### ISSUE THREAD

**Issue by chirags** [YahooArchive/yos-social-objc#1]
YOSRequestClient ignores the query string for PUT requests

Request:
PUT /v1/yql HTTP/1.1
Host: query.yahooapis.com
User-Agent: YosCocoaSdk/0.3 (Mac OS X/10.5.7; en_US;)
Accept: _/_
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Content-Length: 0
Connection: keep-alive

Response
HTTP/1.1 401 Authorization Required
Date: Mon, 20 Jul 2009 07:10:18 GMT
WWW-Authenticate: OAuth oauth_problem="parameter_absent", realm="yahooapis.com"
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml

<?xml version='1.0' encoding='UTF-8'?>
<yahoo:error xmlns:yahoo='http://yahooapis.com/v1/base.rng'
  xml:lang='en-US'>
  yahoo:descriptionPlease provide valid credentials/yahoo:description
/yahoo:error

**Comment by honcheng** [comment]
Hi,
Is this 7 months old bug fixed? 
Is this the same bug that crashes the app when this line of code is executed

```
      - (BOOL)insertUpdateWithTitle:(NSString *)aTitle
           andDescription:(NSString *)aDescription
                  andLink:(NSString *)aLink 
                  andDate:(NSDate *)aDate
                  andSuid:(NSString *)aSuid
```

?
