### ISSUE TITLE
YOSAuthRequest.m causes "Program received signal:  “EXC_BAD_ACCESS”"

### ISSUE THREAD

**Issue by gaiusparx** [YahooArchive/yos-social-objc#4]
In the definition of - (YOSAccessToken *)fetchAccessToken:(YOAuthToken *)requestOrAccessToken withVerifier:(NSString *)verifier.

```
YOSRequestClient *client = [self requestClient];
[client setRequestUrl:url];
[client setHTTPMethod:@"POST"];
[client setRequestParameters:requestParameters];

YOSResponseData *response = [client sendSynchronousRequest];
//[client release];
```

Need to comment out [client release] to avoid the EXC_BAD_ACCESS bomb. As [self requestClient] already return an autorelease object.

**Comment by yahoo** [comment]
Fixed.
