### ISSUE TITLE
Control never comes back to the application after login

### ISSUE THREAD

**Issue by knowsudhanshu** [YahooArchive/yos-social-objc#7]
Hi, I am integrating yos-social-objc in my iPhone application to fetch contact list of a user. When I press the 'connect to yahoo' button in my application it opens up safari where user can enter his credentials to login. But after login it only shows this message "To complete sharing of Yahoo! info with <apphere>, enter code "5xbatf" into <apphere>." and never comes back to the application. I can't find any tutorial for any kind of setting to be done for the application while integrating. Please help.

**Comment by greenchiu** [comment]
i have some problem ... is there any help ?

**Comment by WWM-EMRAN** [comment]
Me having same problem. I have searched the Web for this solution and got nothing effective for this.
Please assist to get me ride of this problem.

**Comment by ykjchen** [comment]
Here's a [stackoverflow answer](http://stackoverflow.com/q/19090688/2880276).

**Comment by aravindkumar** [comment]
Same Problem is faced by me.

**Comment by michaelchum** [comment]
Fixed in the latest revamped SDK. The web view now automatically closes and return to the app upon successful authentication.
