### ISSUE TITLE
crash in iphone5c ios7

### ISSUE THREAD

**Issue by singlee** [YahooArchive/yos-social-objc#9]
it crashes in  iphone5c ios7, cus the code :

```
NSData *connectionResponseData = [NSURLConnection sendSynchronousRequest:urlRequest returningResponse:&urlResponse error:&rspError];
```

urlResponse will be nil in ios7.0, but not nil in other system.

weird.

**Comment by michaelchum** [comment]
Thanks for the report. The SDK has been revamped, it should work with iOS 7 now!
